# Generated by Django 2.0.7 on 2018-07-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.CharField(default='', max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='images')),
                ('brand', models.CharField(default='', max_length=50)),
                ('category', models.CharField(choices=[('MENS_TSHIRTS', 'Mens T-Shirts'), ('MENS_JEANS', 'Mens Jeans'), ('MENS_SHOES', 'Mens Shoes')], default='MENS_TSHIRTS', max_length=30)),
            ],
        ),
    ]
