# Generated by Django 2.0.6 on 2018-07-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180709_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('test', 'test item'), ('MENS_TSHIRTS', 'Mens T-Shirts'), ('MENS_JEANS', 'Mens Jeans'), ('MENS_SHOES', 'Mens Shoes')], default='test', max_length=30),
        ),
    ]
