# Generated by Django 2.0.7 on 2018-07-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180709_1428'),
        ('products', '0003_product_category'),
    ]

    operations = [
    ]
